### PR TITLE
Bump version 0.1.2

### PR DESCRIPTION
**Pull request by osrufung**
Hi @q231950, is that possible to bump the version to include the latest fix? 😊

### CODE REVIEW

**Comment by q231950** [comment]
Absolutely @osrufung ! Sorry as usual for the late reply, I never get GitHub notifications. I messed up my notification settings 😭Send a message [on Twitter](https://twitter.com/q231950) next time 😅

**Comment by q231950** [comment]
p.s. I think I fixed my notifications now 🤞

**Comment by osrufung** [comment]
thank you @q231950! next time I'll spam you by twitter ;)

**Comment by q231950** [comment]
Yes please 😅

P.s. see, immediate response!

**Pull request merged**
